name: aws-v5
on:
  push:
    branches:
      - main
#main 브렌치에 푸쉬가되면 밑에 jobs를 실행한다
#action은 스크립트의 모임이다.레포지토리를 받아야하는데 git init, git fetch or pull로 다운,
#이런 작업들로 레포지토리 코드를 가져옴  이런 것들을 라이브러리 형태로 제공
#actions/checkout@v3 즉 이건 코드 다운로드 하겠다는 말
#actions/setup-java@v3 jdk설치할 수 있게 스크립트(액션) 제공

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.

#runs-on : ubuntu-latest 우분투 최신버전 변경
#distribution 필수임 (벤더사)
#run밑에 shell 제거, 디폴트라서 안적어도 됨
#einaregilsson/beanstalk-deploy@v21 노드 버전 업데이트


jobs:
  build: #build라고안적고 아무거나 적어도됨
    runs-on: ubuntu-latest #ubuntu설치
    steps:
      - name: Checkout #네임은 아무거나 적어도됨
        uses: actions/checkout@v3 #코드 다운로드
      - name: Set up JDK 11
        uses: actions/setup-java@v3 #JDK설치
        with:
          java-version: 11 #v3에서 11을 지원해야 된다. (지원안하면 v번호를 높여보자)
          distribution: zulu #벤더사
      - name: Pemission #이름은 중요하지않음
        run: chmod +x ./gradlew
        shell: bash #기본값 삭제가능
      - name: Build with Gradle
        run: ./gradlew clean build #clean빌드는 빌드폴더를 통쨰로 날리고 새로 만드는 것.
        shell: bash #이건 디폴트라 제거가능
